# qt_5_12_3-win64_msvc2017_64.yml
name: qt_5_12_3-win64_msvc2017_64
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        qt_version: [5.12.3]  #[5.6.3,5.12.3]
        qt_target: [desktop]
        qt_arch: [win64_msvc2017_64] # [win64_msvc2017_64, win32_msvc2017, win32_mingw53,win32_mingw73]
        include:
          - qt_arch: win64_msvc2017_64
            msvc_arch: x64
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_ver }}
          target: ${{ matrix.qt_target }}
          arch: ${{ matrix.qt_arch }}
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build-msvc
        shell: cmd
        env:
          vc_arch: ${{ matrix.msvc_arch }}
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %vc_arch%
          qmake
          nmake
