# qt_5_12_3-win64_msvc2017_64.yml
name: qt_5_12_3-win64_msvc2017_64
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: windows-2019
    strategy:
      matrix:
        qt_ver: [5.12.3]  #[5.6.3,5.12.3]
        qt_target: [desktop]
        qt_arch: [win64_msvc2017_64] # [win64_msvc2017_64, win32_msvc2017, win32_mingw53,win32_mingw73]
        msvc_arch: [x64]
        qt_arch_install: [msvc2017_64]
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_ver }}
          target: ${{ matrix.qt_target }}
          arch: ${{ matrix.qt_arch }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: msvc-build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.msvc_arch }}
          qmake
          nmake
          echo winSdkDir=%WindowsSdkDir% >> %GITHUB_ENV%
          echo winSdkVer=%WindowsSdkVersion% >> %GITHUB_ENV%
          echo vcToolsInstallDir=%VCToolsInstallDir% >> %GITHUB_ENV%
          echo vcToolsRedistDir=%VCToolsRedistDir% >> %GITHUB_ENV%
